---
name: Status updates

'on':
  - status

jobs:
  status:
    name: Show new status
    runs-on: ubuntu-latest

    steps:
      - name: Show new status
        run: |
          cat << EOF
          ${{ toJSON(github.event) }}
          EOF
